version: '3.3'

volumes:
  nyta-db:

services:
  db:
    image: mongo
    volumes:
      - 'nyta-db:/data/db'
    ports:
      - 5555:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yourUsername
      - MONGO_INITDB_ROOT_PASSWORD=yourPassword
    networks:
      - default

  express-back-end:
    build:
      context: ./express-back-end
      dockerfile: Dockerfile
    volumes:
      - './express-back-end:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 5000:5000
    env_file: './express-back-end/.env'
    environment:
      - PORT=5000
    networks:
      - default

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - './front-end:/usr/src/app'
      - '/usr/src/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
    env_file: './front-end/.env'
    depends_on:
      - express-back-end
    networks:
      - default
