version: '3.3'

volumes:
  nyta-db:

services:
  db:
    image: mongo
    volumes:
      - 'nyta-db:/data/db'
    ports:
      - 5555:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yourUsername
      - MONGO_INITDB_ROOT_PASSWORD=yourPassword
    networks:
      - default

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - './back-end:/usr/src/app'
    ports:
      - 5000:5000
    env_file: './back-end/.env'
    networks:
      - default

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - './front-end:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3000
    env_file: './front-end/.env'
    networks:
      - default
    depends_on:
      - back-end

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 81:80
    networks:
      - default
    depends_on:
      - back-end
      - front-end
