version: '3.3'

volumes:
  nyta-db:
  nyta-redis:

services:
  db:
    image: mongo
    volumes:
      - 'nyta-db:/data/db'
    ports:
      - 27017:27017
    environment:
      # The username and passwords that will be user for the database service
      - MONGO_INITDB_ROOT_USERNAME=yourUsername
      - MONGO_INITDB_ROOT_PASSWORD=yourPassword
    networks:
      - default

  redis:
    image: redis
    volumes:
      - 'nyta-redis:/data/'
    networks:
      - default

  express-back-end:
    build:
      context: ./express-back-end
      dockerfile: Dockerfile-prod
    ports:
      - 5000:5000
    env_file: './express-back-end/.env'
    environment:
      - PORT=5000
    networks:
      - default
    depends_on:
      - db

  front-end:
    image: nichtj3/nyta-front-end:prod
    build:
      context: ./front-end
      dockerfile: Dockerfile-prod
    env_file: './front-end/.env'
    networks:
      - default
    depends_on:
      - express-back-end

  nginx:
    image: nichtj3/nyta-nginx:prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - front-end
      - express-back-end
