version: '3.3'

volumes:
  nyta-db:

services:
  db:
    image: mongo
    volumes:
      - 'nyta-db:/data/db'
    ports:
      - 27017:27017
    env_file: './db/.env'
    networks:
      - default

  back-end:
    image: nichtj3/nyta-back-end:prod
    build:
      context: ./back-end
      dockerfile: Dockerfile-prod
    env_file: './back-end/.env'
    networks:
      - default
    depends_on:
      - db
    deploy:
      replicas: 1

  front-end:
    image: nichtj3/nyta-front-end:prod
    build:
      context: ./front-end
      dockerfile: Dockerfile-prod
    env_file: './front-end/.env'
    networks:
      - default
    depends_on:
      - back-end
    deploy:
      replicas: 1

  nginx:
    image: nichtj3/nyta-nginx:prod
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    networks:
      - default
    depends_on:
      - back-end
      - front-end
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
