# the first image use node image as the builder because it has git program
FROM node as builder

WORKDIR /usr/src/app

COPY . .

RUN npm ci

## compile typescript
RUN npm run build

## remove packages of devDependencies
RUN npm prune --production

# ===============
# the second image use node:slim image as the runtime
FROM node:slim as runtime

WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ENV NODE_ENV=production

## Copy the necessary files form builder
COPY --from=builder /usr/src/app/dist/ ./dist
COPY --from=builder /usr/src/app/node_modules/ ./node_modules/
COPY --from=builder /usr/src/app/package.json ./package.json

EXPOSE 8080

CMD [ "npm", "run", "start" ]