name: Docker

on:
  push:
    # Publish `dev` as Docker `latest` image.
    branches:
      - dev

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    name: Build and publish master branch dockerfiles
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v2

      - name: Log into docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build images
        run: docker-compose build

      - name: Push image
        run: docker-compose push
